import Employee from "../models/employee.js";
import mailer from "../lib/mailer.js";
import crypto from "crypto";
import mongoose from "mongoose";

export async function list(req, res) {
  try {
    let filter = {};
    if (!req.user?.isAdmin) {
      const userLevel = Number(req.user?.empLevel || 0);
      filter = { empLevel: { $gte: userLevel - 1, $lte: userLevel } };
    }
    const docs = await Employee.find(filter).sort({ createdAt: -1 }).limit(200);
    res.json({ data: docs });
  } catch (err) {
    res.status(500).json({ error: "Failed to list employees" });
  }
}

export async function get(req, res) {
  const { id } = req.params;
  try {
    let doc = null;
    if (mongoose.isValidObjectId(id)) {
      doc = await Employee.findById(id);
    } else {
      doc = await Employee.findOne({ empCode: Number(id) });
    }
    if (!doc) return res.status(404).json({ error: "Not found" });

    if (!req.user?.isAdmin) {
      const userLevel = Number(req.user?.empLevel || 0);
      const targetLevel = Number(doc.empLevel || 0);
      const canView =
        Number(doc.empCode) === Number(req.user?.empCode) ||
        (targetLevel >= userLevel - 1 && targetLevel <= userLevel);
      if (!canView) {
        return res.status(403).json({ error: "You can only view your level and one lower level employees" });
      }
    }

    res.json({ data: doc });
  } catch (err) {
    res.status(500).json({ error: "Failed to fetch employee" });
  }
}

export async function create(req, res) {
  try {
    const payload = req.body || {};
    // normalize email for checks
    const emailCheck = String(payload.emailId || "").toLowerCase().trim();

    if (emailCheck) {
      const existing = await Employee.findOne({ emailId: emailCheck });
      if (existing) return res.status(409).json({ error: "Email already in use" });
    }
    const totalEmployees = await Employee.countDocuments();

    // Bootstrap flow: first user can be created without auth if marked as admin.
    if (!req.user && totalEmployees > 0) {
      return res.status(401).json({ error: "Unauthorized" });
    }

    if (!req.user && totalEmployees === 0) {
      if (!payload.isAdmin) {
        return res.status(400).json({ error: "First user must be admin" });
      }
    }

    if (req.user && !req.user.isAdmin) {
      return res.status(403).json({ error: "Only admin can create employees" });
    }

    const payloadWithCreator = {
      ...payload,
      createdByName: req.user?.empName || payload.empName || "System",
      createdByEmpCode: req.user?.empCode || null,
      createdByUserId: req.user?.userId || null
    };
    // ensure stored email is normalized
    if (emailCheck) payloadWithCreator.emailId = emailCheck;

    const doc = new Employee(payloadWithCreator);

    // Generate temporary password for newly created users (unless provided)
    function genTempPassword(len = 12) {
      const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
      const bytes = crypto.randomBytes(len);
      let out = "";
      for (let i = 0; i < len; i += 1) out += alphabet[bytes[i] % alphabet.length];
      return out;
    }

    const providedPassword = String(payload.password || "").trim();
    const isPasswordProvided = providedPassword.length > 0;
    const tempPassword = isPasswordProvided ? providedPassword : genTempPassword(12);

    // set password; only force change if password was autogenerated
    doc.setPassword(tempPassword);
    doc.mustChangePassword = isPasswordProvided ? false : true;

    await doc.save();

    // Send account email only when we generated a temporary password
    if (!isPasswordProvided) {
      try {
        const subject = "Your OKR account";
        const text = `Your account has been created. Username: ${doc.userId}\nTemporary password: ${tempPassword}\nPlease change your password on first login.`;
        await mailer.sendEmail({ to: doc.emailId, subject, text });
      } catch (mailErr) {
        console.error("Failed to send account email", { err: mailErr?.message });
      }
    }

    res.status(201).json({ data: doc });
  } catch (err) {
    // handle duplicate key errors gracefully
    if (err && (err.code === 11000 || err.name === "MongoServerError")) {
      const key = err.keyValue && Object.keys(err.keyValue)[0];
      const fieldMap = { emailId: "Email", cellNumber: "Phone", userId: "User ID", empCode: "Employee code" };
      const fieldLabel = fieldMap[key] || key || "Field";
      return res.status(409).json({ error: `${fieldLabel} already exists` });
    }
    res.status(400).json({ error: err.message || "Failed to create" });
  }
}

export async function update(req, res) {
  const { id } = req.params;
  try {
    const incoming = { ...(req.body || {}) };

    // normalize and check email duplication when updating
    if (incoming.emailId) {
      const newEmail = String(incoming.emailId || "").toLowerCase().trim();
      const existing = await Employee.findOne({ emailId: newEmail });
      if (existing) {
        // if existing record is not the one we're updating -> conflict
        if (mongoose.isValidObjectId(id)) {
          if (String(existing._id) !== String(id)) return res.status(409).json({ error: "Email already in use" });
        } else {
          if (Number(existing.empCode) !== Number(id)) return res.status(409).json({ error: "Email already in use" });
        }
      }
      incoming.emailId = newEmail;
    }

    if (!req.user?.isAdmin) {
      const targetEmpCode = mongoose.isValidObjectId(id) ? null : Number(id);
      if (targetEmpCode && targetEmpCode !== Number(req.user.empCode)) {
        return res.status(403).json({ error: "You can update only your own profile" });
      }

      delete incoming.isAdmin;
      delete incoming.empLevel;
      delete incoming.empCode;
    }

    let doc = null;
    if (mongoose.isValidObjectId(id)) {
      doc = await Employee.findById(id);
      if (!doc) return res.status(404).json({ error: "Not found" });

      if (!req.user?.isAdmin && Number(doc.empCode) !== Number(req.user?.empCode)) {
        return res.status(403).json({ error: "You can update only your own profile" });
      }

      Object.assign(doc, incoming);
      await doc.save();
    } else {
      doc = await Employee.findOneAndUpdate(
        { empCode: Number(id) },
        incoming,
        { new: true, runValidators: true }
      );
    }
    if (!doc) return res.status(404).json({ error: "Not found" });
    res.json({ data: doc });
  } catch (err) {
    if (err && (err.code === 11000 || err.name === "MongoServerError")) {
      const key = err.keyValue && Object.keys(err.keyValue)[0];
      const fieldMap = { emailId: "Email", cellNumber: "Phone", userId: "User ID", empCode: "Employee code" };
      const fieldLabel = fieldMap[key] || key || "Field";
      return res.status(409).json({ error: `${fieldLabel} already exists` });
    }
    res.status(400).json({ error: err.message || "Failed to update" });
  }
}

export async function remove(req, res) {
  const { id } = req.params;
  try {
    if (!req.user?.isAdmin) {
      return res.status(403).json({ error: "Only admin can delete employees" });
    }

    let doc = null;
    if (mongoose.isValidObjectId(id)) {
      doc = await Employee.findByIdAndDelete(id);
    } else {
      doc = await Employee.findOneAndDelete({ empCode: Number(id) });
    }
    if (!doc) return res.status(404).json({ error: "Not found" });
    res.json({ data: doc });
  } catch (err) {
    res.status(500).json({ error: "Failed to delete" });
  }
}
